import { AlignLeft, Clapperboard, GalleryHorizontalEnd, Image, ListOrdered, Mail, MonitorPlay, PlaySquare, RectangleVertical, Type } from "lucide-react";

export const SIZES = {
  portrait: { id: "portrait", label: "Portrait", ratio: "4:5", w: 1080, h: 1350, hint: "Instagram and LinkedIn feed" },
  square: { id: "square", label: "Square", ratio: "1:1", w: 1080, h: 1080, hint: "Works everywhere" },
  story: { id: "story", label: "Story", ratio: "9:16", w: 1080, h: 1920, hint: "Stories, Reels, TikTok" },
  landscape: { id: "landscape", label: "Landscape", ratio: "16:9", w: 1200, h: 675, hint: "X, YouTube, link previews" },
  youtube: { id: "youtube", label: "YouTube", ratio: "16:9 HD", w: 1280, h: 720, hint: "Video thumbnails" },
  poster: { id: "poster", label: "Poster", ratio: "A4", w: 1240, h: 1754, hint: "Print and PDF handouts" },
};

// `platform` is the backend pipeline profile used when generating with AI:
// it decides slide count (LinkedIn = 6-slide carousel, the others = one page).
export const KINDS = {
  carousel: {
    id: "carousel",
    label: "Carousel",
    icon: GalleryHorizontalEnd,
    description: "A swipeable multi-slide story",
    platform: "linkedin",
    defaultSize: "portrait",
    sizes: ["portrait", "square", "story"],
  },
  poster: {
    id: "poster",
    label: "Poster",
    icon: RectangleVertical,
    description: "One bold page for announcements and quotes",
    platform: "instagram",
    defaultSize: "portrait",
    sizes: ["portrait", "square", "story", "poster"],
  },
  image: {
    id: "image",
    label: "Image",
    icon: Image,
    description: "A landscape graphic for X, blogs and links",
    platform: "x",
    defaultSize: "landscape",
    sizes: ["landscape", "square", "portrait"],
  },
  thumbnail: {
    id: "thumbnail",
    label: "Thumbnail",
    icon: MonitorPlay,
    description: "A bold YouTube thumbnail with 2 to 5 words",
    platform: "x",
    defaultSize: "youtube",
    sizes: ["youtube", "landscape"],
  },
};

// Text-only outputs. Generated by researching and writing the post, then
// rewriting it into the chosen format (backend/api/ai.py FORMATS).
export const TEXT_FORMATS = {
  x_thread: { id: "x_thread", label: "X thread", icon: ListOrdered, description: "5 to 8 posts, each under 280 characters" },
  linkedin_post: { id: "linkedin_post", label: "LinkedIn post", icon: AlignLeft, description: "A text-only post with a strong first line" },
  instagram_caption: { id: "instagram_caption", label: "Instagram caption", icon: Type, description: "Hook, value, call to action, hashtags" },
  newsletter: { id: "newsletter", label: "Newsletter blurb", icon: Mail, description: "Subject, preview text, and a short teaser" },
  video_script: { id: "video_script", label: "Reels or TikTok script", icon: Clapperboard, description: "Hook, beats, and on-screen text" },
  youtube: { id: "youtube", label: "YouTube titles", icon: PlaySquare, description: "Titles, thumbnail text, and a description" },
};

export const PLATFORMS = [
  { id: "linkedin", label: "LinkedIn" },
  { id: "instagram", label: "Instagram" },
  { id: "x", label: "X" },
];

export function sizeOf(project) {
  return SIZES[project.size] ?? SIZES.portrait;
}

export const SLIDE_LIMIT = 20;
