import {
  BookOpen,
  Brain,
  Calendar,
  Camera,
  ChartColumn,
  CircleCheck,
  Clock,
  Code,
  Coffee,
  DollarSign,
  Flame,
  Globe,
  Heart,
  Lightbulb,
  Megaphone,
  MessageCircle,
  Rocket,
  Shield,
  Sparkles,
  Star,
  Target,
  TrendingUp,
  Trophy,
  Users,
  Zap,
} from "lucide-react";

// Icons a slide can show above its label. Stored on the slide by key.
export const SLIDE_ICONS = {
  lightbulb: Lightbulb,
  trending: TrendingUp,
  target: Target,
  rocket: Rocket,
  zap: Zap,
  check: CircleCheck,
  star: Star,
  heart: Heart,
  users: Users,
  chart: ChartColumn,
  clock: Clock,
  calendar: Calendar,
  shield: Shield,
  sparkles: Sparkles,
  book: BookOpen,
  message: MessageCircle,
  megaphone: Megaphone,
  money: DollarSign,
  globe: Globe,
  code: Code,
  camera: Camera,
  coffee: Coffee,
  trophy: Trophy,
  flame: Flame,
  brain: Brain,
};
