import {
  Bell,
  BookOpen,
  Brain,
  Building2,
  Calendar,
  Camera,
  ChartColumn,
  CircleCheck,
  Clock,
  Cloud,
  Code,
  Coffee,
  Compass,
  Database,
  DollarSign,
  Eye,
  Flag,
  Flame,
  Gift,
  Globe,
  GraduationCap,
  Handshake,
  Heart,
  Layers,
  Leaf,
  Lightbulb,
  Link,
  Lock,
  Mail,
  Map,
  Megaphone,
  MessageCircle,
  Puzzle,
  Repeat,
  Rocket,
  Search,
  Settings,
  Shield,
  ShoppingCart,
  Smartphone,
  Sparkles,
  Star,
  Target,
  TrendingUp,
  Trophy,
  Users,
  Wrench,
  Zap,
} from "lucide-react";

// Icons a slide can show above its label. Stored on the slide by key.
export const SLIDE_ICONS = {
  lightbulb: Lightbulb,
  trending: TrendingUp,
  target: Target,
  rocket: Rocket,
  zap: Zap,
  check: CircleCheck,
  star: Star,
  heart: Heart,
  users: Users,
  chart: ChartColumn,
  clock: Clock,
  calendar: Calendar,
  shield: Shield,
  sparkles: Sparkles,
  book: BookOpen,
  message: MessageCircle,
  megaphone: Megaphone,
  money: DollarSign,
  globe: Globe,
  code: Code,
  camera: Camera,
  coffee: Coffee,
  trophy: Trophy,
  flame: Flame,
  brain: Brain,
  search: Search,
  settings: Settings,
  layers: Layers,
  flag: Flag,
  link: Link,
  lock: Lock,
  map: Map,
  puzzle: Puzzle,
  gift: Gift,
  leaf: Leaf,
  mail: Mail,
  phone: Smartphone,
  cloud: Cloud,
  database: Database,
  cart: ShoppingCart,
  building: Building2,
  school: GraduationCap,
  handshake: Handshake,
  eye: Eye,
  compass: Compass,
  bell: Bell,
  repeat: Repeat,
  tools: Wrench,
};
